services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5332:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meetlog
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
